bingo/randomize_drops.py
bot.py
components/modals.py
components/views.py
config/definitions.py
db/silly_things_for_seedbot_to_say.txt
functions.py
parse_commands.py

Sept 2022 updates

---

functions.py
parse_commands.py

Updating API references to new website - updating local randomizer versions to 1.2.2

1.2.2 update

---

parse_commands.py

- Adjusted replacement of scaling options -- Only CED and CE options are replace with Check scaling (and only Level/HP/MP scaling are evaluated)

2023-05-09 updates to &ap argument

---

functions.py

- Add --hidden arg to hide flagsets from presets

2023-06-01: hidden arg for presets

---

functions.py
parse_commands.py

- add user command '!vamp' to create a yaml for Vampire Survivors

2023-06-05 - Add VS AP yaml creation

---

parse_commands.py

- added &local arg to force seed generation to happen locally instead of on the website

2023-06-13 -- add &local arg

---

parse_commands.py

- Enforced trimmed names in yamls to avoid duplicates for people with names over 12 characters

2023-06-19 -- Updated !weekly command

---

functions.py

2023-09-24 - Minor update

---

.gitmodules
parse_commands.py
run_local.py

* Added WC, WC dev, WC door rando and jdm as submodules
* Added threading for jdm calls
* Assorted delicious code cleanup
* Added !mainpull command for bot admins to pull changes to WC main

2023-11-12 - Update/Bugfix

---

.idea/misc.xml
.idea/vcs.xml
parse_commands.py

2023-11-18 - Bugfix

---

bingo/steve.py

* Updated seed file locations for &steve

2024-01-04: Minor Update

---

functions.py

Noticed that `random.choices` was called way too many times here. I think there are similar issues in the flag builder, but I need to see what WorldsCollide actually does with the flags before I start messing with things.

Low-hanging optimizations

---

cogs/funcs.py
cogs/help.py
cogs/presets.py
functions.py

* Add new user db table
* Add new user commands
* * `/adduser`
* * `/deleteuser`

add user table and related functionality

---

.gitmodules
cogs/funcs.py
cogs/help.py
cogs/seedgen.py
db/practicehelp.txt
db/seedhelp.txt
flag_builder.py
functions.py
run_local.py

This code adds a "practice" version of Final Fantasy 6 Worlds Collide, which itself is a forked branch off of the main FF6WC repo, into Seedbot. 
The practice branch from my fork modifies Worlds Collide to allow a player to choose the Final Kefka fight from the airship as well as recruiting characters beyond the starting party and being able to pick a specific boss/dragon to fight. The practice setting gives the player access to everything else: equip all espers, learn all spells & other command abilities, all characters can equip all items, and you get 6 of every item in the game (due to space limitations), so you can essentially pick and choose how you can fight Kefka or any other boss/dragon in the game. The only settings that matter for the practice seed are: character level, boss …

Practice rom

---

db/presethelp.txt
db/seedhelp.txt
functions.py

* Added &emptyshops arg
* Updated AP template builder to exclude -stesp flag, which is not supported in AP
* Added a 5000 button limit to SeedBot's persistent view to help with boot times

Arg + AP + Button update

---

functions.py

See: https://docs.google.com/document/d/1SuCE-15DwR-OjX2oAv80JMntu32_2WyDxFR1mAYQIqY/edit?tab=t.0
for more details on the new game mode itself and screenshots of the WOB/WOR access unlock objectives. 
This update to Seedbot will add the **&lg1** parameter to Seedbot and roll seeds using the in-development branch of the Location Gating mode on my GitHub.

add location_gating1 submodule for "new" game mode Location Gated

---

db/presethelp.txt
db/seedhelp.txt
functions.py

Forces the -lg1 flag and adds default objectives to access WOB and WOR.

Add &lg1 for new game mode Location Gating

---

cogs/funcs.py
db/presethelp.txt
db/seedhelp.txt
functions.py
run_local.py

Another variation of location gating, this time called Searching For Friends can be played by using &lg2. This will add an objective to unlock WOR via Floating Continent Escape and an objective to unlock WOB by either Save Cid or Let Cid Die.

Add Searching For Friends game mode

---

flag_builder.py
functions.py

_NOTE: Any of these options can be over-written by the options flags!!!_
**Default: !practice**
Use -prac flag
Party & Boss Level 40
Stats: 80%-125%
All commands (Lore, Rage, SwdTech, Blitz, Dance, Tools, Magitek upgrade)
No Possess
All espers
Learn all spells
All items (6 of each, may update this if I incorporate AddItems instruction from Discord)
Restoratives
Throwables
100% equips
**Ultros League: !practice –ul**
Use -prac3 flag (do not give all items, instead simulate opening chests & shopping)
Stats: 80%-125%
Party Level: 35-45 at random (normally what levels you’d be for final Kefka)
Boss Level 30-40 at random (6c+9e = 15 * 2 = 30 minimum boss level, 40 max scaling)
SwdTech
50/50 chance of SwdTech 8 unlocked (simulate doing Cyan’s Dream objective)
Otherwise, SwdTech based on party …

Add More Options to Practice ROM

---

flag_builder.py

See https://docs.google.com/document/d/1wqlcJaF9cKctThJZptIyBwy4-Q__wKBvpYFx43YxPsk/edit?tab=t.0

add more options to practice
